export { default as IconFacebook } from './IconFacebook.vue'
export { default as IconTwitter } from './IconTwitter.vue'
export { default as IconLinkedin } from './IconLinkedin.vue'
export { default as IconInstagram } from './IconInstagram.vue'
export { default as IconSearch } from './IconSearch.vue'
